# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-03 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infographic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='Publication date')),
                ('visible', models.BooleanField(default=False, verbose_name='Visible')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Title')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Description')),
                ('sponsored', models.BooleanField(default=False, verbose_name='Sponsored')),
                ('ad', models.BooleanField(default=False, verbose_name='Ad')),
                ('slug', models.CharField(blank=True, max_length=180, null=True, verbose_name='Slug')),
            ],
            options={
                'ordering': ('pub_date', 'title'),
            },
        ),
        migrations.CreateModel(
            name='MetaInfographic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(blank=True, max_length=5, null=True, verbose_name='Language code')),
                ('medium_img', models.ImageField(blank=True, max_length=500, null=True, upload_to='', verbose_name='Medium image')),
                ('thumbnail_img', models.ImageField(blank=True, max_length=500, null=True, upload_to='', verbose_name='Thumbnail')),
                ('high_def_url', models.CharField(blank=True, max_length=150, null=True, verbose_name='URL to high definition infographic')),
                ('infographic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.Infographic')),
            ],
            options={
                'ordering': ('infographic__pub_date', 'infographic__title'),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tag')),
                ('description', models.CharField(blank=True, max_length=150, null=True, verbose_name='Description')),
                ('infographics', models.ManyToManyField(to='public.Infographic')),
            ],
            options={
                'ordering': ('tag',),
            },
        ),
    ]
