# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-09 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infographic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField(default=django.utils.timezone.now, verbose_name='Publication date')),
                ('last_update_date', models.DateField(default=django.utils.timezone.now, verbose_name='Last update date')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('title', models.CharField(max_length=140, verbose_name='Title')),
                ('description', models.CharField(max_length=140, verbose_name='Description')),
                ('sponsored', models.BooleanField(default=False, verbose_name='Sponsored')),
                ('ad', models.BooleanField(default=False, verbose_name='Ad')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('medium_img', models.ImageField(max_length=500, upload_to='', verbose_name='Medium image')),
                ('thumbnail_img', models.ImageField(max_length=500, upload_to='', verbose_name='Thumbnail')),
            ],
            options={
                'ordering': ('pub_date', 'title'),
            },
        ),
        migrations.CreateModel(
            name='InfographicURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL to high definition infographic')),
                ('infographic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.Infographic')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=70, null=True, verbose_name="Language's name")),
                ('code', models.CharField(blank=True, max_length=5, null=True, verbose_name="Language's code (5 characters max.)")),
            ],
            options={
                'ordering': ('code', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tag')),
                ('description', models.CharField(blank=True, max_length=150, null=True, verbose_name='Description')),
            ],
            options={
                'ordering': ('tag',),
            },
        ),
        migrations.AddField(
            model_name='infographicurl',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.Language'),
        ),
        migrations.AddField(
            model_name='infographic',
            name='tags',
            field=models.ManyToManyField(to='public.Tag'),
        ),
    ]
