# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-19 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infographic',
            options={'ordering': ('-pub_date', 'title')},
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default=None, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
