# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-11-14 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_auto_20171019_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfographicSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True, verbose_name="URL to infographic's source")),
                ('infographic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.Infographic')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.Language')),
            ],
        ),
    ]
