# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-08 17:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_auto_20170903_2112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infographic',
            options={'ordering': ('meta_infographic__pub_date', 'meta_infographic__title')},
        ),
    ]
