# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-11-14 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_infographicsource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infographicsource',
            name='title',
            field=models.CharField(max_length=140, verbose_name='Title'),
        ),
    ]
