# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-03-24 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def migrate_infographiccontent(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    infographics = apps.get_model("public", "Infographic").objects.using(db_alias).all()
    infographic_content = apps.get_model("public", "InfographicContent")
    english_language = apps.get_model("public", "Language").objects.using(db_alias).filter(code="en").first()

    for infographic in infographics:
        hd_url = apps.get_model("public", "InfographicURL").objects.using(db_alias).filter(language=english_language).first()
        infographic_content = infographic_content(
            last_update_date = infographic.last_update_date,
            title = infographic.title,
            description = infographic.description,
            slug = infographic.slug,
            medium_img = infographic.medium_img,
            thumbnail_img = infographic.thumbnail_img,
            infographic = infographic,
            language = english_language,
            hd_url = hd_url,
        )
        infographic_content.save()


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_auto_20181114_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfographicContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update_date', models.DateField(default=django.utils.timezone.now, verbose_name='Last update date')),
                ('title', models.CharField(max_length=140, unique=True, verbose_name='Title (translated)')),
                ('description', models.CharField(max_length=140, verbose_name='Description')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('medium_img', models.ImageField(max_length=500, upload_to='', verbose_name='Medium image')),
                ('thumbnail_img', models.ImageField(max_length=500, upload_to='', verbose_name='Thumbnail')),
                ('hd_url', models.URLField(blank=True, null=True, verbose_name='URL to high definition infographic')),
            ],
        ),
        migrations.AddField(
            model_name='infographiccontent',
            name='infographic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.Infographic'),
        ),
        migrations.AddField(
            model_name='infographiccontent',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.Language'),
        ),
        migrations.RunPython(migrate_infographiccontent),
        migrations.RemoveField(
            model_name='infographicurl',
            name='infographic',
        ),
        migrations.RemoveField(
            model_name='infographicurl',
            name='language',
        ),
        migrations.AlterModelOptions(
            name='infographic',
            options={},
        ),
        migrations.RemoveField(
            model_name='infographic',
            name='ad',
        ),
        migrations.RemoveField(
            model_name='infographic',
            name='description',
        ),
        migrations.RemoveField(
            model_name='infographic',
            name='medium_img',
        ),
        migrations.RemoveField(
            model_name='infographic',
            name='thumbnail_img',
        ),
        migrations.AlterField(
            model_name='infographic',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='infographic',
            name='title',
            field=models.CharField(max_length=140, unique=True, verbose_name='Title (identifier)'),
        ),
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True, verbose_name="Language's code (5 characters max.)"),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(blank=True, max_length=70, null=True, unique=True, verbose_name="Language's name"),
        ),
        migrations.DeleteModel(
            name='InfographicURL',
        ),
    ]
