# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-02 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_auto_20170908_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfographicURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL to high definition infographic')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=70, null=True, verbose_name="Language's name")),
                ('code', models.CharField(blank=True, max_length=5, null=True, verbose_name="Language's code (5 characters max.)")),
            ],
            options={
                'ordering': ('code', 'name'),
            },
        ),
        migrations.RemoveField(
            model_name='metainfographic',
            name='tags',
        ),
        migrations.AlterModelOptions(
            name='infographic',
            options={'ordering': ('pub_date', 'title')},
        ),
        migrations.RemoveField(
            model_name='infographic',
            name='high_def_url',
        ),
        migrations.RemoveField(
            model_name='infographic',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='infographic',
            name='meta_infographic',
        ),
        migrations.AddField(
            model_name='infographic',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='infographic',
            name='ad',
            field=models.BooleanField(default=False, verbose_name='Ad'),
        ),
        migrations.AddField(
            model_name='infographic',
            name='description',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='infographic',
            name='pub_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Publication date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='infographic',
            name='slug',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='infographic',
            name='sponsored',
            field=models.BooleanField(default=False, verbose_name='Sponsored'),
        ),
        migrations.AddField(
            model_name='infographic',
            name='tags',
            field=models.ManyToManyField(to='public.Tag'),
        ),
        migrations.AddField(
            model_name='infographic',
            name='title',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Title'),
        ),
        migrations.DeleteModel(
            name='MetaInfographic',
        ),
        migrations.AddField(
            model_name='infographicurl',
            name='infographic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.Infographic'),
        ),
        migrations.AddField(
            model_name='infographicurl',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.Language'),
        ),
    ]
