# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-02 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_auto_20171002_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infographic',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Slug'),
        ),
    ]
