# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2019-03-25 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0006_auto_20190325_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infographic',
            name='slug',
        ),
    ]
