# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-08 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0006_auto_20171002_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infographic',
            name='pub_date',
            field=models.DateField(blank=True, null=True, verbose_name='Publication date'),
        ),
    ]
