# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-08 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0007_auto_20171008_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infographic',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Publication date'),
        ),
    ]
