# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-08 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0008_auto_20171008_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='infographic',
            name='last_update_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Last update date'),
        ),
    ]
